packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.2.11

dedupeInjectedDeps: false

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - playwright-chromium
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd

overrides:
  '@types/estree': ^1.0.8
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  ignoreMissing:
    # ignore react-server-dom-webpack -> webpack
    - webpack
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  '@voidzero-dev/vite-plus': latest
